### ISSUE TITLE
Respect compilation-scroll-output

### ISSUE THREAD

**Issue by jetaggart** [pezra/rspec-mode#105]
I think this is a better solution than auto scrolling at the end. That way the auto scroll flag can be removed and rspec-mode can defer to the user's compilation scroll preferences

**Comment by jetaggart** [comment]
I'm happy to take a stab at this.

**Comment by dgutov** [comment]
Would you just remove the variable, and the let-binding in `rspec-compile`?

I don't know if we really want that, but `define-compilation-mode` has a mechanism for  custom vars in compilation-mode derivatives. If `rspec-auto-scroll` was called `rspec-compilation-scroll-output`, its value would be used automatically.

**Comment by jetaggart** [comment]
I think so. If you don't bind `compilation-scroll-output` explicitly in the let, will it not just respect your global setting?

**Comment by jetaggart** [comment]
It feel weird to have this set in two places.

**Comment by dgutov** [comment]
> If you don't bind compilation-scroll-output explicitly in the let, will it not just respect your global setting?

It should. Please go ahead and submit the patch.
