### ISSUE TITLE
Doesn't use rvm.el gemset setting?

### ISSUE THREAD

**Issue by mordocai** [pezra/rspec-mode#110]
I'm not sure whether this is actually an rvm.el problem or rspec mode problem so apologies if it turns out to be a rvm.el problem.

The only maybe related issue I could find was https://github.com/senny/rvm.el/issues/27.

I have the following in my init.el:

    (setq rvm--gemset-default "my-desired-gemset")
    (rvm-use-default)
    (defadvice rspec-compile (around rspec-compile-around)
      "Use BASH shell for running the specs because of ZSH issues."
      (let ((shell-file-name "/bin/bash"))
        ad-do-it))

    (ad-activate 'rspec-compile)

When I do an rspec-verify I get:

-*- mode: rspec-compilation; default-directory: "~/git_repos/\<redacted\>" -*-
RSpec Compilation started at Wed Feb 11 15:59:40

bundle exec rake spec SPEC_OPTS='--options /Users/\<redacted\>/git_repos/\<redacted\>/.rspec' SPEC='/Users/\<redacted\>/git_repos/\<redacted\>/spec/controllers/\<redacted\>_spec.rb'
Could not find parser-2.2.0.2 in any of the sources
Run `bundle install` to install missing gems.

RSpec Compilation exited abnormally with code 7 at Wed Feb 11 15:59:40

My gemset has all gems required (including parser-2.2.0.2) but the global gemset doesn't. Doing a bundle install while using the global gemset "fixes" this issue.

I am on Mac OS X using the latest version of RVM, rvm.el, and rspec-mode with the brew installed stable emacs.

Any ideas on how to fix this? I specifically do not want to pollute the global gemset.

**Comment by dgutov** [comment]
Yes, the aforementioned issue looks very much related. And anyway, we don't do anything special with RVM or `rvm.el` here, so any improvement would have to be done in the latter (whether it's a bug or a missing feature, is a different question).

Personally, I'd recommend using `rbenv`, which doesn't need any special integration. I also don't think gemsets are a good idea: this task is better left to Bundler.

**Comment by rranelli** [comment]
I agree with @dgutov about `rbenv`. Since I moved away from `rvm` to `rbenv` + `bundler` I had absolutely no problems with ruby versions, gems and whatsoever.
