### ISSUE TITLE
re: top level describe blocks

### ISSUE THREAD

**Issue by imtayadeway** [pezra/rspec-mode#115]
The current recommended way to declare top level describe blocks is as follows:

```ruby
RSpec.describe "SUT" do
  # ...
end
```
Could this be a feature that rspec-mode would want to support?

**Comment by dgutov** [comment]
What kind of support would you like to see? In snippets?

**Comment by imtayadeway** [comment]
Snippets, yes. I like that I get a snippet when I create a new spec file, but find that I am changing them by hand to conform with the above. I'm happy to try to tackle this if you think that's something you'd want. Apologies for opening this with a terribly vague request!

**Comment by pezra** [comment]
@imtayadeway, <https://github.com/pezra/rspec-mode/blob/master/snippets/rspec-mode/desc> and <https://github.com/pezra/rspec-mode/blob/master/snippets/rspec-mode/descm> should be updated to use this style since it is now the recommendation. If you submitted a PR to that effect we'd merge it.

**Comment by pezra** [comment]
Hmm... upon further consideration :smile: we probably should have new snippets since the `RSpec.` bit is only needed at the top level. Maybe `tdesc` and `tdescm`?

**Comment by dgutov** [comment]
@pezra I don't think we need that: the `desc` snippet already checks whether it's a the top level, and if so, behaves differently (`descm` should probably do the same).

This feature could be implemented to see whether there's a match for `expose_dsl_globally *= *false` in `spec/spec_helper.rb`, or just check a user option. Either would only take effect when `top-level` is t.

**Comment by imtayadeway** [comment]
@pezra and @dgutov thanks for the recommendations - i'll try to cook something up tonight and get back to you.

**Comment by dgutov** [comment]
Implemented and merged.
