### ISSUE TITLE
FactoryGirl: rspec--include-fg-syntax-methods-p

### ISSUE THREAD

**Issue by imtayadeway** [pezra/rspec-mode#117]
Just noticed that this checks the spec helper for `FactoryGirl::Syntax::Methods`. More recent versions of rspec-rails will create a `spec_helper.rb` and `rails_helper.rb` file, and the appropriate place for putting this include is in the latter. Should the rails helper also be checked (assuming of course that it's a rails project, and that the rails helper is there)?

**Comment by dgutov** [comment]
Sure, why not?

**Comment by imtayadeway** [comment]
@dgutov great! I'll see if I can tackle this over the next few days.
