### ISSUE TITLE
Incorrect spec file path for files in nonstandard directories

### ISSUE THREAD

**Issue by jbaum98** [pezra/rspec-mode#123]
In addition to the standard Rails directory structure, I have other root level directories like `services` or `exhibits`:
```
├── app
        ├── assets
        ├── controllers
        ├── helpers
        ├── mailers
        ├── models
        └── views
├── config
├── db
├── exhibits
├── Gemfile
├── Gemfile.lock
├── lib
├── log
├── public
├── services
├── spec
└── tmp
```
When I execute `rspec-toggle-spec-and-target` in a file in one of those nonstandard directories like `services` outside of `app`, it opens a buffer for a new file directly inside of `spec`, instead of the existing file in `/spec/services`.

**Comment by dgutov** [comment]
Yeah, that one's been bothering me for a while, too. I'll create a pull request adding a new user option and reversing a bit of current logic in this area.
