### ISSUE TITLE
RSpec Compilation segmentation fault

### ISSUE THREAD

**Issue by pmontrasio** [pezra/rspec-mode#131]
I have this kind of errors whenever I run rspec from within emacs.

    -*- mode: rspec-compilation; default-directory: "~/Documents/my-project/" -*-
    RSpec Compilation started at Sat Oct 31 09:23:57
    
    bundle exec rake spec SPEC_OPTS='--options /home/me/Documents/my-project/.rspec' SPEC='/home/me/Documents/my-project/spec/controllers/my_controller_spec.rb:82'

    RSpec Compilation segmentation fault (core dumped) at Sat Oct 31 09:23:57

The same command works when run from the shell (bash on Ubuntu 12.04).

I'm using rvm with rvm-mode. The ruby versions and the gemset are set correctly, following the prompts of rvm-mode.

I have no idea if this is due to rspec-mode or something else but I'm starting from here: did anybody experience something like that? Thanks.

Emacs is GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.4.2) of 2014-02-22 on king, modified by Debian.

    rspec-mode         20151003.315 installed  Enhance ruby-mode for RSpec
    rvm                20140109.319 installed  Emacs integration for rvm

I also have inf-ruby

     Status: Installed in `/home/me/.emacs.d/elpa/inf-ruby-20141005.550/'.
    Version: 20141005.550

**Comment by pmontrasio** [comment]
I'm closing this because I found the same problem when running a Ruby interpreter with inf-ruby. I opened an issue there https://github.com/nonsequitur/inf-ruby/issues/78

**Comment by dgutov** [comment]
> did anybody experience something like that?

I haven't. But you might be one of the first people trying Ruby 2.2.3 with Emacs.

**Comment by pedz** [comment]
FYI: I'm using ruby 2.2.3p173 and emacs 24.5 and the latest rspec-mode without issues.  I was using 24.3 a few weeks ago with the same version of ruby.  And I believe I was using an old version of rspec-mode until recently.  I am not using RVM.
