### ISSUE TITLE
Do not require Vagrantfile to run tests via Vagrant

### ISSUE THREAD

**Issue by thegeorgeous** [pezra/rspec-mode#145]
Although it is a good practice to check if Vagrantfile is present, it is a problem if I have multiple folders in my project, all of which are inside the `/vagrant` folder. In which case, the vagrant option is completely ignored. It would be helpful if the vagrant variables were scoped to a project rather than as global variables.

**Comment by dgutov** [comment]
> It would be helpful if the vagrant variables were scoped to a project rather than as global variables.

Could you elaborate?

**Comment by thegeorgeous** [comment]
`rspec-vagrant-cwd` is set globally. One project I work on is in `/vagrant/myproject` on one of my VMs, while another is in `/vagrant` on a different VM. I end up setting the `rspec-vagrant-cwd` variable everytime I switch the project. If it were possible to store such settings in a dotfile or something in each project, it would be much easier to switch between different projects. It could potentially help avoid the `Vagrantfile` check too.
