### ISSUE TITLE
Spacemacs deletes it: Found 1 orphan package(s) to delete

### ISSUE THREAD

**Issue by phstc** [pezra/rspec-mode#146]
I every time I restart [Spacemacs](http://spacemacs.org/), it shows a message:

```
emacs conflict installing Found 1 orphan package(s) to delete...
```

And deletes `rspec-mode`.

Any ideas?

**Comment by dgutov** [comment]
Here's a better place to ask: https://gitter.im/syl20bnr/spacemacs
