### ISSUE TITLE
Copy last test command to clipboard

### ISSUE THREAD

**Issue by Kukunin** [pezra/rspec-mode#158]
I think it'd useful to have a command (with keybinding) to copy last rspec command to clipboard.

It may be useful to run rspec in terminal (to run `pry` or with extra keys, such as `- b`)

**Comment by pezra** [comment]
That would be useful. Any chance you could create a PR for that?

**Comment by Kukunin** [comment]
hm.. good chance to try elisp. I'll try to prepare

**Comment by dgutov** [comment]
Merged.
