### ISSUE TITLE
How to customize rspec erorr stack colours matching with my preferred theme.

### ISSUE THREAD

**Issue by amritfd** [pezra/rspec-mode#160]
Hi,
It seems the rspec mode color is using some different colour scheme. How to change it to something which suits my current theme. All my error stack are not visible in emacs. I have attached one image also. Please take a look and guide me to do my work. I cant live without this rspec mode. I use it in every minute. Thanks.

<img width="1321" alt="screen shot 2017-03-05 at 12 27 25 am" src="https://cloud.githubusercontent.com/assets/21101155/23581479/a2054d3c-013a-11e7-81a6-82608ea1704d.png">

**Comment by dgutov** [comment]
To find out the face which is used at a given buffer position, move the cursor there and type `C-u C-x =`. That is the face you need to customize or ask the author of the current theme to include.

For example, the errors are highlighted with the face `compilation-error`.

**Comment by amritfd** [comment]
Hi,
Thanks for replying.  `compilation-error` is not reflecting in the error. For example in my below screenshot, `compilation-error` is magenta but the face is something else. I shown the output of `C-u C-x =` also. 
<img width="1434" alt="screen shot 2017-03-05 at 2 13 13 am" src="https://cloud.githubusercontent.com/assets/21101155/23582135/b27b3f5a-0149-11e7-87d6-69d56fe2611a.png">

**Comment by dgutov** [comment]
Ah yes, that also happens. See the `foreground-color` value above? That is there because of `rspec-colorize-compilation-buffer` we add to `compilation-filter-hook`, to translate the ANSI codes that the RSpec process outputs into Emacs faces.

You can try undoing this in `rspec-compilation-mode-hook`, if that is your goal. Personally, I'd just pick a theme that works well with the generic colors.

**Comment by amritfd** [comment]
Hi,
I checked the code for `rspec-compilation-mode-hook`. If I comment out the `rspec-colorize-compilation-buffer`, then also its coming same. Find the attached screenshot please. Commenting this line should not override the face is it?

<img width="680" alt="screen shot 2017-03-05 at 1 42 04 pm" src="https://cloud.githubusercontent.com/assets/21101155/23585667/fbd84dfe-01a9-11e7-859e-1991d876867d.png">

**Comment by dgutov** [comment]
It should.

What does `C-u C-x =` show then?

**Comment by amritfd** [comment]
It shows like this - 

<img width="585" alt="screen shot 2017-03-05 at 2 11 48 pm" src="https://cloud.githubusercontent.com/assets/21101155/23585821/e46ec27a-01ad-11e7-835e-8e083358c3c9.png">

**Comment by amritfd** [comment]
After restarting emacs twice. I can see the face changed. But the hyper link seems to have broken. Previous setting was better now I feel. Anyway I am good now. Thanks. :)
