### ISSUE TITLE
Multiple rspec processes at the same time

### ISSUE THREAD

**Issue by kzkn** [pezra/rspec-mode#169]
How do I run multiple rspec processes without killing the first rspec process? When I tried it, my Emacs says:

```
compilation-start: Cannot have two processes in ‘*rspec-compilation*’ at once
```

**Comment by pezra** [comment]
Running more than one rspec process is not supported. 

I think this could be implemented in rspec-mode. I'd welcome that functionality. If you are interested feel free to submit a PR.
