### ISSUE TITLE
Error for rspec-compile-target-directory

### ISSUE THREAD

**Issue by avit** [pezra/rspec-mode#172]
Since the update in #170, I'm getting the error:

```rspec-compile: Symbol’s function definition is void: (setf rspec-compile-target-directory)```

I am using rspec-mode with Spacemacs. The same error happens for any target (project, buffer, single). Let me know if there's some more information you need to help debug.

/cc @kzkn

**Comment by bixuanzju** [comment]
I am having the same issue here.

**Comment by kzkn** [comment]
Here is a workaround (until a bug fix is released):

```
M-x load-file
/path/to/rspec-mode.el
```

**Comment by pezra** [comment]
fixed in 1.19
