### ISSUE TITLE
Running `rspec-verify-matching` uses wrong full path to matched files

### ISSUE THREAD

**Issue by bfad** [pezra/rspec-mode#179]
When in a test file and running `rspec-verify-matching` via `C-c , m`, I get an error that the file it tries to run doesn't exist. For example, the file will be in `/path/to/rails_app/spec/controllers/api/example_controller_spec.rb` and running `rspec-verify-matching` will produce the following log:

```
bundle exec rspec --format documentation `/path/to/rails_app/spec/controllers/api/spec/controllers/api/example_controller_spec.rb`
bundler: failed to load command: rspec (/path/to/ruby/2.4.0/bin/rspec)
LoadError: cannot load such file -- /path/to/rails_app/spec/controllers/api/spec/controllers/api/example_controller_spec.rb
```

In the above example I'm only expecting it to match one file, but even when I expect it to match multiple files, it still manages to put the directory the current file exists in as the prefix to all the other relative paths of matching files. One example when running from `/path/to/rails_app/spec/controllers/api/users_controller_spec.rb` I get the following:

```
bundle exec rspec --format documentation /path/to/rails_app/spec/controllers/api/spec/controllers/account/users_controller_spec.rb /path/to/rails_app/spec/controllers/api/spec/controllers/api/users_controller_spec.rb /path/to/rails_app/spec/controllers/api/spec/controllers/users_controller_spec.rb /path/to/rails_app/spec/controllers/api/spec/engines/admin/controllers/admin/users_controller_spec.rb
```

**Comment by dgutov** [comment]
> bundler: failed to load command: rspec (/path/to/ruby/2.4.0/bin/rspec)

Isn't this a different problem? About failing to find the `rspec` command?

**Comment by dgutov** [comment]
> it still manages to put the directory the current file exists in as the prefix to all the other relative paths of matching files

This indeed looks wrong, though.

**Comment by bfad** [comment]
It doesn't fail to find the `rspec` command, `rspec` is failing to find the path to the file because the path has been prefixed with the path to the current file's directory. Running `rspec-verify-single` and `rspec-verify` for the file works just fine.

**Comment by bfad** [comment]
@kzkn Just tried your patch and `rspec-verify-matching` is indeed working with that patch. Thank you!

**Comment by dgutov** [comment]
That PR is now merged. Please let us know if the problem remains.
