### ISSUE TITLE
How disable rspec -b backtrace options

### ISSUE THREAD

**Issue by zirni** [pezra/rspec-mode#189]
Hello folks,

I'm using spacemacs' ruby layer to run my local rspec files and it's outputing the whole backtrace of a failing spec.
The problem is that the runners' cmd contains the -b option'
```bin/rspec -b /home/.../model_spec.rb```
Just walked through the code and can't find how to disable this particular option.

Would be glad to get some tips from you guys.

Thanks a lot.
zirni

**Comment by dgutov** [comment]
Hi!

I don't get any `-b`. What code are you referring to?

**Comment by zirni** [comment]
Found the appropriate variable to change this behaviour:
https://github.com/ruby-test-mode/ruby-test-mode/blob/master/ruby-test-mode.el#L72

`ruby-test-mode` add the `-b` option which is part of the spacemacs ruby layer
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/ruby/packages.el#L26
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/ruby/packages.el#L29

Sorry for popping up an issue here  because it's not related to rspec-mode package.

For the folks searching for this problem in this package - here a quick solution for spacemacs:
```
(ruby :variables ruby-test-rspec-options nil)
```
