### ISSUE TITLE
rspec-verify et. al. not split window if target compile buffer already in another frame

### ISSUE THREAD

**Issue by pedz** [pezra/rspec-mode#52]
Not sure how to mark this as a 'feature' or 'suggestion'

I usually work with one frame with emacs but I'm toying with multiple frames (and I'm also toying with testing a great deal recently).  I put the "_rspec-compilation_" buffer in its own separate frame and then run (or re-run) rspec-verify (or any of the other similar test centric commands) and the separate frame is updated like I want but the code still splits the current frame (the one with the spec in it where I issued the command) and displays another copy of the same buffer in the new window.

For me, I'd like for that to not happen.  Just the one instance of the buffer it its own frame is all I want to see and leave the originating frame alone.  In this way, I can set up frames and windows with what I want to see and work on and doing the test could just update the appropriate windows but does not change the window configuration. 

I predict that there are others that want to see it both places.  I don't know if this is a feature of Emacs' compilation or if rspec is doing this.

**Comment by sadhu89** [comment]
Hey @pedz. Thanks!!! I added `(setq display-buffer-reuse-frames t)` to my emacs config and it worked!
Do you know if it is possible than when I click on the link of the rspec-compilation buffer of a failed spec it opens the file in the other frame?

**Comment by pedz** [comment]
@sadhu89 No.  You can view my emacs set up on my github account https://github.com/pedz/my.emacs.d  Maybe grep around and for various options to see how I set thingsl
